// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkateAppikene.Data;

#nullable disable

namespace SkateAppikene.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601175035_AddPinLevel")]
    partial class AddPinLevel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SkateAppikene.Models.Pin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pins");
                });

            modelBuilder.Entity("SkateAppikene.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kasutajanimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParkImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParkName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SkateAppikene.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eesnimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kasutajanimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoodudKuupäev")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParoolHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Perenimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
